# Generated by Django 5.1 on 2024-09-24 10:15

import artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='artists_images/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='debut_year',
            field=models.IntegerField(validators=[artist.models.validate_year]),
        ),
    ]
