# Generated by Django 5.1 on 2024-09-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth_name',
            new_name='birth_date',
        ),
    ]
